### ISSUE TITLE
kstatus in cli-utils vs kustomize

### ISSUE THREAD

**Issue by Raffo** [kubernetes-sigs/cli-utils#196]
I'm trying to build a small CLI to solve the problem of waiting on kubernetes resources to reach they desired state, for example when deploying a new version of an application to a cluster. 
I saw that the `kstatus` code lives here and in [the kustomize repo](https://github.com/kubernetes-sigs/kustomize/tree/master/kstatus) as well. Can someone shed a light on which one is the officially maintained code? Are they exactly the same code? Which one is recommended to import in a third party project? 

Thanks in advance! 🙇

**Comment by mortent** [comment]
@Raffo The official maintained version of the code is in this repo. The code that is in the Kustomize repo is an older version and it is no longer maintained.

**Comment by Raffo** [comment]
@mortent thank you for the answer. Should I go ahead and make a PR to delete the code in kustomize? If we can reduce confusion for other people that'd be great. Otherwise, a note in the Readme should also be okay. WDYT?

**Comment by mortent** [comment]
@Raffo I have removed the kstatus code from Kustomize. Thanks for pointing it out.
