### ISSUE TITLE
add options to continue applying when encountering on errors

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/cli-utils#266]
Add an option `AbortOnErrors` in the ApplyOption. When it is `false`, the apply doesn't return on an error immediately. Instead, it should try apply all resources. For each resource, the returned event should capture the error if any.

**Comment by seans3** [comment]
Some context: `kubectl apply` should "ContinueOnError", which is the default behavior. The current version of `kubectl` included in cli-utils does not, but that is a bug. Upgrading to using `kubectl` >= 1.18 should fix the bug.

**Comment by mortent** [comment]
For kpt, I think we need to consider "FailOnError" as a feature, not as a bug. No matter what the original intention, it has never actually continued on error. I agree though that upgrading the kubectl libraries is a good idea, but we need to support both continue-on-error and fail-on-error.

**Comment by Liujingfang1** [comment]
@seans3 Thanks for sharing the "ContinueOnError" in 1.18 kubectl. I'll take a look at that. @mortent In the kpt library, we need to provide an option for the apply behavior on error. By that option, the CLI will fail-on-error and the consumer of that library can choose continue-on-error.

**Comment by Liujingfang1** [comment]
Per offline discussion, we decided the apply process to be continue-on-error by default. The process has the following steps:
1. (optional) Create the namespace for the inventory object if it doesn't exist
2. update the inventory object with the union of last applied objects and current objects
3. apply current objects
4. prune last applied objects
5. update the inventory object to remove the last applied objects from the inventory list

#### step 1 and step 2
- If it fails to create the namespace, the process exists with an error.
- If it fails to update the inventory object, the process exits with an error.

Once the inventory object is updated, the process should be continued to the last step of updating the inventory object even if some error occurs when applying/pruning an object.

#### step 3
For every resource being applied, it sends out an event.
- If the resource is successfully applied, send out an ApplyEvent without error
- If the resource is failed to be applied, send out an ApplyEvent with an error

#### step4 
For every resource being pruned, it sends out an event.
- If the resource is successfully pruned, send out a PruneEvent without error
- If the resource is failed to be pruned, send out a PruneEvent with an error

#### step5
In the final step of updating the inventory object, the inventory list includes the union of the current set of objects and the previous objects that are failed to be pruned.

**Comment by Liujingfang1** [comment]
Fixed via #286
