### ISSUE TITLE
change the Apply interface to use inventory.Inventory instead of unstructured.Unstructured

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/cli-utils#267]
Change the Applier.Run from
```
func (a *Applier) Run(ctx context.Context, objects []*unstructured.Unstructured,
options Options) <-chan event.Event {}
```
to
```
func (a *Applier) Run(ctx context.Context, inventory inventory.Inventory, objects []*unstructured.Unstructured,
options Options) <-chan event.Event {}
```

**Comment by mortent** [comment]
I know that my suggested api in https://github.com/kubernetes-sigs/cli-utils/pull/245 has the `InventoryInfo` as a real type, but I think we should consider making it an interface. For the Applier implementation we only need to be able to look up the name, namespace and id of the inventory. If we make this an interface, it would be possible for implementations of the Provider interface to turn it into a more specific type that could contain additional information that is only applicable to certain Provider implementations.

**Comment by Liujingfang1** [comment]
Agreed. It should be an interface. I'll use this one for now https://github.com/kubernetes-sigs/cli-utils/blob/master/pkg/inventory/inventory.go#L32. If other functions are needed from the interface, we'll update it.
