### ISSUE TITLE
the library needs a function to apply a single resource to the cluster

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/cli-utils#298]
Besides the main apply function 
```
Applier.Run(Context, InventoryInfo, []*Unstructured, option)
```

we also need the function to apply a single resource.

```
Applier.DetachResourceFromInventory(Context, InventoryInfo, *Unstructured)
```
It removes the `owning-inventory` annotation from the resource and applies it.
It also removes the identifier for that resource from the Inventory list.

**Comment by seans3** [comment]
We should not add this function. We should only need to re-run the apply to remove the annotation and update the inventory. I'll close this shortly.

**Comment by Liujingfang1** [comment]
The `owning-inventory` is added during the apply, re-run it doesn't remove the annotation.

**Comment by Liujingfang1** [comment]
I'll do this in the kpt repo. Closing this issue.
