### ISSUE TITLE
Status for Job in-progress

### ISSUE THREAD

**Issue by jlordiales** [kubernetes-sigs/cli-utils#329]
Hi!
I'm curious about the reasoning behind https://github.com/kubernetes-sigs/cli-utils/blob/535f781a3c1b1d66b06a93f59e7a03c03af81477/pkg/kstatus/status/core.go#L488-L490, specifically `it will have the Current status while the job is running and after it has been completed successfully`.

Why isn't `InProgress` the returned status for a job that is currently in-progress? Wouldn't that be more intuitive if you want to poll until the job has either succeeded (status: `Current`) or failed (status: `Failed`)?

**Comment by mortent** [comment]
@jlordiales 
So the primary goal for the kstatus library is to determine what we call "reconcile status", i.e. whether the desired state as expressed by a KRM resource has been fully realized in the cluster. In practice this means we want to report whether the controllers have completed their work on the resource. This is pretty intuitive for resources like Deployments, but trickier for a resource like Job. But to be consistent, a Job is considered reconciled if it has started (there is additional complexity here around how we should treat a job that starts but fails almost immediately..).

But you are not the first to ask about this, so we do want to make this configurable. We don't have a design for this yet, but I'm thinking that we will support an annotation that users can apply to a job and this will cause kstatus to wait until the job has completed.

**Comment by jlordiales** [comment]
Got it! Looking forward to the configuration option for this. 

I'll go ahead and close this issue. Thanks!
