### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by ash2k** [kubernetes-sigs/cli-utils#347]
Hi! I'm thinking of starting to use this project and I have some questions.

1. Is there a KEP? I don't see anything https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli
2. Is there a roadmap document? Any documents? I only found some notes in the meeting agenda doc.
3. Anything I should be aware of?
4. This repo depends on kubectl. Shouldn't it be the other way around (i.e. binary depends on library) - perhaps it's a temporary state of things?

Thanks. If it works well for me (which I think it will, based on what I see in the code), I'd like to start contributing to the project.

p.s. thanks a lot for building this stuff as a reusable library!

**Comment by hiddeco** [comment]
> This repo depends on kubectl. Shouldn't it be the other way around (i.e. binary depends on library) - perhaps it's a temporary state of things?

:heavy_plus_sign: We have been consuming this library for awhile now to benefit from `kstatus`, and [have noticed](https://github.com/fluxcd/kustomize-controller/pull/343#issuecomment-838411472) that this precise dependency causes issues while being used together with (newer) Kustomize dependencies as it pulls in a (very) old version of Kustomize (`v2.0.3`).

One way to work around this, while maintaining the `cmd` (examples?) would be to release the libraries in this repository as separate Go modules, as this would limit the number of (obsolete) dependencies being pulled in.

**Comment by ash2k** [comment]
I have stumbled upton this doc https://github.com/GoogleContainerTools/kpt/blob/master/docs/ROADMAP.md, which answers my question sufficiently.
