### ISSUE TITLE
kstatus reports that a deployment is in progress, while that is not the case

### ISSUE THREAD

**Issue by Shaked** [kubernetes-sigs/cli-utils#357]
I am using Rancher as part of my continuous deployment. AFAIU rancher uses kstatus while trying to figure what is the current deployment(s) status and then reports back to its UI. 

However, it seems like that the following lines are triggered although all deployments are in a Running state. 

https://github.com/kubernetes-sigs/cli-utils/blob/8200fe56434dbb4fa897912524793af3c3384828/pkg/kstatus/status/core.go#L120-L123

My current assumption is that because there are more than 1 deployments within the package that is being installed, then kstatus sees N deployments and N-1 successes because one of them wasn't changed at all and therefore didn't trigger an update. 

I was wondering if this could be a bug, and what would be the best way to verify that? 

Thank you 
Shaked

**Comment by mortent** [comment]
@Shaked So the kstatus library only considers each workload (deployment, statefulset...) individually. So whether multiple deployments are updated at the same time won't affect the reconcile status.

The code in question here only applies to StatefulSets and only matters if the `partition` property is set on the StatefulSet. So are you seeing situations where the desired number of pods in a StatefulSet has been updated but the kstatus library still reports it as being `InProgress`?

**Comment by Shaked** [comment]
@mortent Unfortunately I can't remember what happened here. Closing and if it pops up again I will post more details. Thank you
