### ISSUE TITLE
Feature Request: Validation Error Handling

### ISSUE THREAD

**Issue by karlkfi** [kubernetes-sigs/cli-utils#484]
There's two schools of thought when handling validation:
1. Skip objects that fail validation and apply everything else
2. Exit early if any objects fail validation

## Option 1: Centralized Deployment Automation

Option 1 is desirable when the scope of the applied resources spans multiple domains (ex: multiple unrelated Deployments).

Option 1 is common with users that have a monorepo style deployment strategy, where multiple applications/systems share deployment automation. This is common when the organization follows "Ops Team" style ownership of deployment.

Pros:
- It's less work to automate in one place and have one team mange it.
- Makes it easier to coordinate deployment between application/system dependencies. 

Cons:
- If everything is applied all together, any one failure can block other unrelated applications/systems from updating or even break them with partial deployment.
- Up front validation would block applying of unrelated applications/systems.
- All applications/systems are deployed with the same client user account, requiring effective root permissions.

## Option 2: Distributed Deployment Automation

Option 2 is desirable when the scope of the applied resources maps to a single domain (ex: a single Deployment with it's immediate dependencies, ConfigMap, Secret, Service, Ingress, etc).

Option 2 is common with users that have a multi-repo or microservice style deployment strategy, where each application/system has its own deployment automation (even if they share common tooling). This is common when the organization follows "DevOps" style ownership of deployment.

Pros:
- Each repo/microservice acts as its own failure domain. If deployment fails, it should only affect that system and its downstream dependents.
- Up front validation can block applying, preventing broken deployments.
- Each applications/systems can be deployed with the different client user account, allowing least-privilege deployment security.

Cons:
- Requires more tooling and training to have multiple teams managing their own deployment automation.
- Makes it harder to coordinate deployment between application/system dependencies in different repos with different deployment automation. 

## Conclusion

Since both systems are viable and expected, cli-utils probably needs to support both.

## Proposal

One way to support both would be to add `ValidationEvents` and a new applier/destroyer option to `ExitOnValidationError` (or `RequireValidation`). This would continue to execute validation up front (and there's more we could add, like validating feature annotations), but instead of always sending an ErrorEvent and exiting, it would send a ValidationEvent for each failure and then only send an ErrorEvent and exit if the ExitOnValidationError flag was set.

Since the current behavior is to exit on validation failure, we could default ExitOnValidationError to true to retain that behavior. However, the event changes might be reverse incompatible, because it doesn't make a lot of sense to send the validation errors both individually and all together in the ErrorEvent.

**Comment by karlkfi** [comment]
Another more complex solution could be to include support for optional failure domains by annotation (ex: `config.kubernetes.io/failure-domain: your-name-here`).

This would allow users of Option 1 deployment strategy to annotate resources with a domain name. Then cli-utils would treat each domain as an independent group of resources. With this pattern, the applier would still send ValidationEvents but instead of exiting on validation failure, it would skip all the resources in the domain with a validation error and continue to apply all the other domains.

**Comment by mortent** [comment]
So I think there are two types of validation that can be useful:
* Client-only validation: This means we verify that resources are valid KRM resources, that annotations (such as depends-on and the apply-time mutations) are well-formed, and possibly validate against the openAPI schema. But we would do this without actually connecting to the cluster.
* Cluster validation: This means actually talking to the cluster to do the validation. This could mean doing server-side dry-run of the resources, or just connect to the cluster to fetch the actual openAPI schema.

I think we want to make sure as much of the validation as possible (in particular for the client-only validation) is separate from the actual library. This means users can shift the validation left and run it as part of their CI/CD pipelines. They can also choose to run it directly prior to actuation if they prefer that.

As for cluster validation, I'm wondering to what extent this is different than the current dry-run behavior? Do we need something that is separate?

No matter what, we do need to handle errors that come up during apply. Are you suggesting that we would send Validation events when we encounter errors during apply? I'm thinking that in those cases we should handle it similarly to how we handle resources that fail for other reasons, so just send ApplyEvent with an error that explains why a resource couldn't be applied.

**Comment by haiyanmeng** [comment]
> I think we want to make sure as much of the validation as possible (in particular for the client-only validation) is separate from the actual library. This means users can shift the validation left and run it as part of their CI/CD pipelines. They can also choose to run it directly prior to actuation if they prefer that.

For the dependsOn feature, the following two types of errors does not require talking to the cluster:
1) CyclicDependenciesError: when there are cyclic dependencies between resources.
2) DeleteResourcesHavingDependentsError: when the customers try to delete a resource without deleting all its dependents.

However, to catch these two types of errors require the dependency graph. There are two options:
1) cli-utils provides an API for accessing the dependency graph of a resource set;
2) the users of cli-utils need to build the dependency graph on its own.

Based on our former discussion, it seems that cli-utils does not want to expose an API for accessing the dependency graph.

**Comment by seans3** [comment]
> > I think we want to make sure as much of the validation as possible (in particular for the client-only validation) is separate from the actual library. This means users can shift the validation left and run it as part of their CI/CD pipelines. They can also choose to run it directly prior to actuation if they prefer that.
> 
> For the dependsOn feature, the following two types of errors does not require talking to the cluster:
> 
> 1. CyclicDependenciesError: when there are cyclic dependencies between resources.
> 2. DeleteResourcesHavingDependentsError: when the customers try to delete a resource without deleting all its dependents.
> 
> However, to catch these two types of errors require the dependency graph. There are two options:
> 
> 1. cli-utils provides an API for accessing the dependency graph of a resource set;
> 2. the users of cli-utils need to build the dependency graph on its own.
> 
> Based on our former discussion, it seems that cli-utils does not want to expose an API for accessing the dependency graph.

Clients should think in terms of the API, not the implementation. Clients should not need to know the `depends-on` functionality is implemented as a graph. For any type of error you expect with `depends-on` functionality, you should look to an ErrorEvent returned on the ErrorChannel that returns the information the client needs. The first `CyclicDependencyError` you described is a already captured:

https://github.com/kubernetes-sigs/cli-utils/blob/master/pkg/object/graph/graph.go#L139

I don't quite understand the second error.

**Comment by haiyanmeng** [comment]
> I don't quite understand the second error.

Image an inventory including three resources: `A`, `B`, and `C`. 
`C` depends on `B`, and `B` depends on `A`. 
If the users delete `B` without deleting `C`, `DeleteResourcesHavingDependentsError` should happen.

**Comment by karlkfi** [comment]
I wasn’t necessarily trying to get into how to handle all errors for this FR. I mainly wanted to focus on the handling of up front validation that the user may want to either cause exit or continue by skipping the invalid resource.

Right now validation failure causes an ErrorEvent and errors cause immediate exit. 

If we wanted, we could make ErrorEvents optionally terminal with some sort of flag on them, but I figured a ValidationEvent would be potentially better UX with clearer meaning. That would let us carve off the obvious validation errors without needing to rewrite how we handle all the other errors. 

But if some clients want to make as many errors as possible non-terminal, then we need to decide to audit all possible errors and decide which ones must be terminal and which ones just cause that resource to be skipped. 

Currently we send apply/prune/delete/wait events with the Skipped operation, but if we start skipping objects before even getting to the task runner, we need to send an event that says why.

**Comment by mortent** [comment]
I think we should at first primarily focus on making sure we handle errors in a sane way for the case where the user wants to apply as many resources as possible, even when there are errors. I agree with @karlkfi here that we need to figure out how to handle this when we encounter these errors before we even get to the task runner. I think the guiding principle here should be that the error handling as seen from the client shouldn't distinguish between whether it happens before we get to the task runner or not. I do see that might be non-trivial, as we currently have a pretty tight coupling between the events and the tasks.

I'm a bit uncertain about the ValidationEvent, as it seems like a validation failure would lead to one or more resources not being applied to the cluster, and therefore be considered an error for a specific resource (or maybe more than one). I would then assume this means that in those case we will leave resources in the live state as they are (i.e. no-op). Or do we have examples of validation errors that doesn't fit into this framework?

I do think detecting as many errors as possible before actually making changes to the live state is super useful for many use-cases. But I'm a bit uncertain how much of this we should make available prior to actually performing the actuation against a cluster (so shift left) and to what extent it should be covered by the dry-run functionality.

**Comment by karlkfi** [comment]
> I'm a bit uncertain about the ValidationEvent, as it seems like a validation failure would lead to one or more resources not being applied to the cluster, and therefore be considered an error for a specific resource (or maybe more than one).

We already have skipped operations on ApplyEvent/PruneEvent/DeleteEvent/WaitEvent. If we don't want to add another event, we can mark the object as skipped in the TaskContext and add a check in the other tasks to send the skipped event, but then we would need to also store the reason why it was skipped in the TaskContext, which seems hacky and inconsistent with the existing TaskContext flags.

We already send the InitEvent from the Applier & Destroyer before executing the task runner. So it's already acting as an "InitTask". I suppose we could send an InitEvent per resource, but that seems like overkill, and the InitEvent already includes other information about what ActionGroups to expect. 

If we use a ValidationEvent, it can include a detailed reason, like `[metadata.name: Required value: name is required, metadata.namespace: Required value: namespace is required]` and then store the validation failure in the TaskContext. Subsequent ApplyEvent/PruneEvent/DeleteEvent/WaitEvent would consider the object skipped and send a hardcoded reason, like `failed validation`.

**Comment by mortent** [comment]
I agree with the alternatives here, and there are some compelling arguments for the ValidationEvent approach. Are you thinking of ValidationEvent as a new top-level event or somehow combining it with the previous discussion around a WarningEvent? I'm also curious to when it would be appropriate to send ValidationEvents, i.e. should clients be prepared to receive those events at any point during the operation?

**Comment by karlkfi** [comment]
> Are you thinking of ValidationEvent as a new top-level event or somehow combining it with the previous discussion around a WarningEvent?

Yes. Top Level. Tho, if desired, we could maybe wrap it in an ActionGroup like the tasks. I don't know if that will provide much value tho.

> I'm also curious to when it would be appropriate to send ValidationEvents, i.e. should clients be prepared to receive those events at any point during the operation?

In my current PR, these only happen up front before any other task. The objects that don't pass validation are then skipped and don't get any apply/prune/wait events.

If you know of any validation that needs to happen later, let me know, but i think the behavior of the ExitEarly option might be confusing if there are delayed validation errors. So I'd like to catch them all up front. For example, I moved the object sorting forward so it could return multiple validation errors, rather than exiting on its first error.
