### ISSUE TITLE
Fix or reduce frequency or switch off perma-failing jobs

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/cli-utils#620]
Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

Additional Context:
https://github.com/kubernetes/test-infra/issues/18600

| CI Job | Days Failed |
| --- | --- |
| [cli-utils-presubmit-master](https://testgrid.k8s.io/sig-cli-misc#cli-utils-presubmit-master)  |  80   |                                           
| [cli-utils-presubmit-master-e2e](https://testgrid.k8s.io/sig-cli-misc#cli-utils-presubmit-master-e2e)  |  80 |                                              
| [cli-utils-presubmit-master-stress](https://testgrid.k8s.io/sig-cli-misc#cli-utils-presubmit-master-stress)  | 80 |

**Comment by mortent** [comment]
I think the jobs are fine, they just happen to only run on presubmit, and the code in this project is pretty stable. We have just had a long-running PR with some runs where the tests have failed. But we will keep an eye on it.

**Comment by dims** [comment]
thanks @mortent feel free to close this
