### ISSUE TITLE
Archive the repository?

### ISSUE THREAD

**Issue by ash2k** [kubernetes-sigs/cli-utils#636]
@seans3 @karlkfi @mortent Hi! If this repo is not maintained (example: https://github.com/kubernetes-sigs/cli-utils/pull/625), perhaps it'd be better for the community if it's archived? It'd be a clear signal that this code should not be used.

Perhaps the community of users can instead move to a fork, such as https://github.com/fluxcd/cli-utils.

WDYT?

FYI @stefanprodan

**Comment by mortent** [comment]
This is maintained, although I agree the response time has been far longer than should be expected over the last several months. There has just been other things going on that the team has been focused on. I'll try to do better going forward.

**Comment by ash2k** [comment]
This is great news, thank you!
