### ISSUE TITLE
Specifying current directory as argument to init produces invalid resource

### ISSUE THREAD

**Issue by mortent** [kubernetes-sigs/cli-utils#87]
Running `kapply init .` produces a grouping object with a label with the form `cli-utils.sigs.k8s.io/inventory-id: .-167716`. Labels are not allowed to have values that start with `.`, so this causes `kapply apply .` to fail.

**Comment by seans3** [comment]
An initial fix will probably expand `.` to the absolute current working directory. But another approach which sounds tempting is use a UUID as the groupname, since it really only needs to be unique. User could override it with the `--group-name` flag if they want something more readable.
